integrates model-provider service (#9)
* integrates model-provider service

* adds project_id to model-provider request

* removes project_id and revision from model-provider api calls

* try auto select model dir

* adds error message if model is deleted during creation

Co-authored-by: JWittmeyer <jens.wittmeyer@onetask.ai>

diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,6 +1,8 @@
 #!/bin/bash
 trap "echo -ne '\nstopping container...' && docker stop refinery-embedder > /dev/null 2>&1 && echo -ne '\t\t [done]\n'" EXIT
 
+source check_config_service
+
 HOST_IP=$(docker network inspect bridge --format='{{json .IPAM.Config}}' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | tail -1)
 
 echo -ne 'stopping old container...'
@@ -11,6 +13,20 @@ echo -ne 'building container...'
 docker build -t refinery-embedder-dev -f dev.Dockerfile .
 echo -ne '\t\t [done]\n'
 
+MODEL_DIR=${PWD%/*}/dev-setup/model-data/
+if [ ! -d "$MODEL_DIR" ] 
+then
+    MODEL_DIR=${PWD%/*/*}/dev-setup/model-data/
+    if [ ! -d "$MODEL_DIR" ] 
+    then
+        # to include volume for local development, use the dev-setup model data folder:  
+        # alternative use manual logic with
+        # -v /path/to/dev-setup/model-data:/models \
+        echo "Can't find model data directory: $MODEL_DIR -> stopping" 
+        exit 1
+    fi
+fi
+
 echo -ne 'starting...'
 docker run -d --rm \
 --name refinery-embedder \
@@ -20,12 +36,15 @@ docker run -d --rm \
 -e S3_SECRET_KEY=r6ywtR33!DMlaL*SUUdy \
 -e POSTGRES=postgresql://postgres:onetask@graphql-postgres:5432 \
 -e DOC_OCK=http://refinery-doc-ock:80 \
+-e MODEL_PROVIDER=http://refinery-model-provider:80 \
 -e WS_NOTIFY_ENDPOINT="http://refinery-websocket:8080" \
 -e NEURAL_SEARCH=http://refinery-neural-search:80 \
 --mount type=bind,source="$(pwd)"/,target=/app \
 -v /var/run/docker.sock:/var/run/docker.sock \
+-v "$MODEL_DIR":/models \
 --network dev-setup_default \
 refinery-embedder-dev > /dev/null 2>&1
 echo -ne '\t\t\t [done]\n'
+
 
 docker logs -f refinery-embedder
